name: Deploy Docusaurus

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd my-website
          npm install

      - name: Build Docusaurus
        run: |
          cd my-website
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }} # Create a GitHub Personal Access Token
          publish_dir: ./my-website/build
          publish_branch: gh-pages

      - name: 🎉 Afficher le message de succès
        run: echo "✅ C'est passé chef !"

